<?php

/**
 * ApplicantStudiesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApplicantStudiesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ApplicantStudiesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApplicantStudies');
    }
}