<?php

/**
 * ApplicantLanguageSkillsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApplicantLanguageSkillsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ApplicantLanguageSkillsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApplicantLanguageSkills');
    }
}