<?php

/**
 * ApplicantSkillsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApplicantSkillsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ApplicantSkillsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApplicantSkills');
    }
}