<?php

/**
 * AssignmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssignmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssignmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Assignment');
    }
}