<?php

/**
 * JobFamilyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobFamilyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobFamilyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobFamily');
    }
}