<?php

/**
 * JobLanguageSkillsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobLanguageSkillsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobLanguageSkillsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobLanguageSkills');
    }
}