<?php

/**
 * JobOfferTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobOfferTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobOfferTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobOffer');
    }
}