<?php

/**
 * JobOfferStudiesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobOfferStudiesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobOfferStudiesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobOfferStudies');
    }
}