<?php

/**
 * JobRequiredSkillsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobRequiredSkillsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobRequiredSkillsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobRequiredSkills');
    }
}