<?php

/**
 * MobilityAreaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MobilityAreaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MobilityAreaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MobilityArea');
    }
}