<?php

/**
 * NationalityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NationalityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NationalityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Nationality');
    }
}