<?php

/**
 * SkillTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SkillTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SkillTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Skill');
    }
}