<?php

/**
 * StudyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Study');
    }
}