<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('job_offer', 'job_offer_location_id_location_id');
        $this->createForeignKey('job_offer', 'job_offer_location_location_id', array(
             'name' => 'job_offer_location_location_id',
             'local' => 'location',
             'foreign' => 'id',
             'foreignTable' => 'location',
             ));
        $this->createForeignKey('job_offer', 'job_offer_assignment_assignment_id', array(
             'name' => 'job_offer_assignment_assignment_id',
             'local' => 'assignment',
             'foreign' => 'id',
             'foreignTable' => 'assignment',
             ));
        $this->createForeignKey('job_offer', 'job_offer_required_experience_experience_id', array(
             'name' => 'job_offer_required_experience_experience_id',
             'local' => 'required_experience',
             'foreign' => 'id',
             'foreignTable' => 'experience',
             ));
        $this->createForeignKey('job_offer_studies', 'job_offer_studies_job_offer_id_job_offer_id', array(
             'name' => 'job_offer_studies_job_offer_id_job_offer_id',
             'local' => 'job_offer_id',
             'foreign' => 'id',
             'foreignTable' => 'job_offer',
             ));
        $this->addIndex('job_offer', 'job_offer_location', array(
             'fields' => 
             array(
              0 => 'location',
             ),
             ));
        $this->addIndex('job_offer', 'job_offer_assignment', array(
             'fields' => 
             array(
              0 => 'assignment',
             ),
             ));
        $this->addIndex('job_offer', 'job_offer_required_experience', array(
             'fields' => 
             array(
              0 => 'required_experience',
             ),
             ));
        $this->addIndex('job_offer_studies', 'job_offer_studies_job_offer_id', array(
             'fields' => 
             array(
              0 => 'job_offer_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('job_offer', 'job_offer_location_id_location_id', array(
             'name' => 'job_offer_location_id_location_id',
             'local' => 'location_id',
             'foreign' => 'id',
             'foreignTable' => 'location',
             ));
        $this->dropForeignKey('job_offer', 'job_offer_location_location_id');
        $this->dropForeignKey('job_offer', 'job_offer_assignment_assignment_id');
        $this->dropForeignKey('job_offer', 'job_offer_required_experience_experience_id');
        $this->dropForeignKey('job_offer_studies', 'job_offer_studies_job_offer_id_job_offer_id');
        $this->removeIndex('job_offer', 'job_offer_location', array(
             'fields' => 
             array(
              0 => 'location',
             ),
             ));
        $this->removeIndex('job_offer', 'job_offer_assignment', array(
             'fields' => 
             array(
              0 => 'assignment',
             ),
             ));
        $this->removeIndex('job_offer', 'job_offer_required_experience', array(
             'fields' => 
             array(
              0 => 'required_experience',
             ),
             ));
        $this->removeIndex('job_offer_studies', 'job_offer_studies_job_offer_id', array(
             'fields' => 
             array(
              0 => 'job_offer_id',
             ),
             ));
    }
}