<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('job_offer', 'job_offer_location_id_location_id', array(
             'name' => 'job_offer_location_id_location_id',
             'local' => 'location_id',
             'foreign' => 'id',
             'foreignTable' => 'location',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('job_offer', 'job_offer_location_id_location_id');
    }
}