<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addjoboffer extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('job_offer', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'job_reference' => 
             array(
              'type' => 'string',
              'length' => 50,
             ),
             'internal_title' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'external_title' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'status' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'openings_number' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'openings_remaining' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'start_date' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'end_date' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'asap' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'opening_cause' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'cause_comments' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'job_family' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'location' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'assignment' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'mission' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'required_experience' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'required_experience_description' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'required_skills_description' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'required_education_description' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'is_budgeted' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'salary' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'contract_kind' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('job_offer');
    }
}