<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addapplication extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('application', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'civil_status' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'first_name' => 
             array(
              'type' => 'string',
              'length' => 50,
             ),
             'last_name' => 
             array(
              'type' => 'string',
              'length' => 50,
             ),
             'birth_date' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'nationality_1' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'nationality_2' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'tel' => 
             array(
              'type' => 'string',
              'length' => 50,
             ),
             'mobile' => 
             array(
              'type' => 'string',
              'length' => 50,
             ),
             'email' => 
             array(
              'type' => 'string',
              'length' => 50,
             ),
             'is_employed' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'current_job' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'availability_period' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'availability_infos' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'activity' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'cv' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'cover_letter' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'work_experience' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'work_experience_description' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'education_description' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'job_wished' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'wished_location' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'is_mobile' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'mobility_area' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'wished_salary' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'job_offer_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('application');
    }
}