<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addjoblanguageskills extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('job_language_skills', array(
             'job_offer_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'language_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'job_offer_id',
              1 => 'language_id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('job_language_skills');
    }
}