<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addjobofferstudies extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('job_offer_studies', array(
             'job_offer_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'study_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'job_offer_id',
              1 => 'study_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('job_offer_studies');
    }
}