<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('job_offer_studies', array(
             'job_offer_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'study_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'job_offer_id',
              1 => 'study_id',
             ),
             ));
        $this->createTable('study', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeColumn('job_offer', 'location_id');
        $this->addColumn('job_offer', 'location', 'integer', '8', array(
             ));
        $this->addColumn('job_offer', 'assignment', '', '', array(
             ));
        $this->addColumn('job_offer', 'required_experience', '', '', array(
             ));
    }

    public function down()
    {
        $this->dropTable('job_offer_studies');
        $this->dropTable('study');
        $this->addColumn('job_offer', 'location_id', 'integer', '8', array(
             ));
        $this->removeColumn('job_offer', 'location');
        $this->removeColumn('job_offer', 'assignment');
        $this->removeColumn('job_offer', 'required_experience');
    }
}