<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('application', 'application_job_offer_id_job_offer_id', array(
             'name' => 'application_job_offer_id_job_offer_id',
             'local' => 'job_offer_id',
             'foreign' => 'id',
             'foreignTable' => 'job_offer',
             ));
        $this->createForeignKey('application', 'application_nationality_1_nationality_id', array(
             'name' => 'application_nationality_1_nationality_id',
             'local' => 'nationality_1',
             'foreign' => 'id',
             'foreignTable' => 'nationality',
             ));
        $this->createForeignKey('application', 'application_nationality_2_nationality_id', array(
             'name' => 'application_nationality_2_nationality_id',
             'local' => 'nationality_2',
             'foreign' => 'id',
             'foreignTable' => 'nationality',
             ));
        $this->createForeignKey('application', 'application_availability_period_availability_period_id', array(
             'name' => 'application_availability_period_availability_period_id',
             'local' => 'availability_period',
             'foreign' => 'id',
             'foreignTable' => 'availability_period',
             ));
        $this->createForeignKey('application', 'application_activity_job_family_id', array(
             'name' => 'application_activity_job_family_id',
             'local' => 'activity',
             'foreign' => 'id',
             'foreignTable' => 'job_family',
             ));
        $this->createForeignKey('application', 'application_work_experience_experience_id', array(
             'name' => 'application_work_experience_experience_id',
             'local' => 'work_experience',
             'foreign' => 'id',
             'foreignTable' => 'experience',
             ));
        $this->createForeignKey('application', 'application_job_wished_contract_kind_id', array(
             'name' => 'application_job_wished_contract_kind_id',
             'local' => 'job_wished',
             'foreign' => 'id',
             'foreignTable' => 'contract_kind',
             ));
        $this->createForeignKey('application', 'application_mobility_area_mobility_area_id', array(
             'name' => 'application_mobility_area_mobility_area_id',
             'local' => 'mobility_area',
             'foreign' => 'id',
             'foreignTable' => 'mobility_area',
             ));
        $this->createForeignKey('job_offer', 'job_offer_status_status_id', array(
             'name' => 'job_offer_status_status_id',
             'local' => 'status',
             'foreign' => 'id',
             'foreignTable' => 'status',
             ));
        $this->createForeignKey('job_offer', 'job_offer_location_location_id', array(
             'name' => 'job_offer_location_location_id',
             'local' => 'location',
             'foreign' => 'id',
             'foreignTable' => 'location',
             ));
        $this->createForeignKey('job_offer', 'job_offer_assignment_assignment_id', array(
             'name' => 'job_offer_assignment_assignment_id',
             'local' => 'assignment',
             'foreign' => 'id',
             'foreignTable' => 'assignment',
             ));
        $this->createForeignKey('job_offer', 'job_offer_required_experience_experience_id', array(
             'name' => 'job_offer_required_experience_experience_id',
             'local' => 'required_experience',
             'foreign' => 'id',
             'foreignTable' => 'experience',
             ));
        $this->createForeignKey('job_offer', 'job_offer_job_family_job_family_id', array(
             'name' => 'job_offer_job_family_job_family_id',
             'local' => 'job_family',
             'foreign' => 'id',
             'foreignTable' => 'job_family',
             ));
        $this->createForeignKey('job_offer', 'job_offer_contract_kind_contract_kind_id', array(
             'name' => 'job_offer_contract_kind_contract_kind_id',
             'local' => 'contract_kind',
             'foreign' => 'id',
             'foreignTable' => 'contract_kind',
             ));
        $this->createForeignKey('job_offer_studies', 'job_offer_studies_job_offer_id_job_offer_id', array(
             'name' => 'job_offer_studies_job_offer_id_job_offer_id',
             'local' => 'job_offer_id',
             'foreign' => 'id',
             'foreignTable' => 'job_offer',
             ));
        $this->createForeignKey('job_required_skills', 'job_required_skills_job_offer_id_job_offer_id', array(
             'name' => 'job_required_skills_job_offer_id_job_offer_id',
             'local' => 'job_offer_id',
             'foreign' => 'id',
             'foreignTable' => 'job_offer',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('application', 'application_job_offer_id_job_offer_id');
        $this->dropForeignKey('application', 'application_nationality_1_nationality_id');
        $this->dropForeignKey('application', 'application_nationality_2_nationality_id');
        $this->dropForeignKey('application', 'application_availability_period_availability_period_id');
        $this->dropForeignKey('application', 'application_activity_job_family_id');
        $this->dropForeignKey('application', 'application_work_experience_experience_id');
        $this->dropForeignKey('application', 'application_job_wished_contract_kind_id');
        $this->dropForeignKey('application', 'application_mobility_area_mobility_area_id');
        $this->dropForeignKey('job_offer', 'job_offer_status_status_id');
        $this->dropForeignKey('job_offer', 'job_offer_location_location_id');
        $this->dropForeignKey('job_offer', 'job_offer_assignment_assignment_id');
        $this->dropForeignKey('job_offer', 'job_offer_required_experience_experience_id');
        $this->dropForeignKey('job_offer', 'job_offer_job_family_job_family_id');
        $this->dropForeignKey('job_offer', 'job_offer_contract_kind_contract_kind_id');
        $this->dropForeignKey('job_offer_studies', 'job_offer_studies_job_offer_id_job_offer_id');
        $this->dropForeignKey('job_required_skills', 'job_required_skills_job_offer_id_job_offer_id');
    }
}